name: Publish Docker Image to GHCR

on:
  push:
    branches: ["master"]  # 触发条件：main分支推送时执行

env:
  IMAGE_NAME: "node-webpage-print"  # 镜像名称
  VERSION: "latest"     # 版本标签

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # 必须授权packages的写入权限

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # 使用GitHub用户名
          password: ${{ secrets.CR_PAT }}  # 引用PAT密钥

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }}